alter table public.trip_checklist_items add column if not exists visibility text not null default 'shared' check(visibility in ('shared','personal'));
drop policy if exists "members read checklist" on public.trip_checklist_items;
create policy "members read allowed checklist" on public.trip_checklist_items for select to authenticated
using(public.is_trip_member(trip_id) and (visibility='shared' or created_by=auth.uid() or assigned_to=auth.uid()));
drop policy if exists "members create checklist" on public.trip_checklist_items;
create policy "members create allowed checklist" on public.trip_checklist_items for insert to authenticated
with check(created_by=auth.uid() and public.is_trip_member(trip_id) and (visibility='shared' or assigned_to=auth.uid()));
create policy "creators delete checklist" on public.trip_checklist_items for delete to authenticated
using(created_by=auth.uid() or exists(select 1 from public.trips t where t.id=trip_id and t.owner_id=auth.uid()));

create or replace function public.toggle_trip_checklist(target_item uuid,target_done boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not exists(select 1 from public.trip_checklist_items i where i.id=target_item and public.is_trip_member(i.trip_id) and (i.visibility='shared' or i.created_by=auth.uid() or i.assigned_to=auth.uid())) then raise exception 'ไม่พบรายการหรือไม่มีสิทธิ์'; end if;
  update public.trip_checklist_items set is_done=target_done,completed_by=case when target_done then auth.uid() else null end,completed_at=case when target_done then now() else null end where id=target_item;
end; $$;

create table if not exists public.product_analytics (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  trip_id uuid references public.trips(id) on delete cascade,
  event_name text not null check(event_name in ('trip_created','invite_created','location_started','expense_created','push_enabled','pwa_installed','calendar_exported','backup_exported','checklist_created')),
  surface text,
  created_at timestamptz not null default now()
);
alter table public.product_analytics enable row level security;
create policy "users insert privacy safe analytics" on public.product_analytics for insert to authenticated
with check(user_id=auth.uid() and (trip_id is null or public.is_trip_member(trip_id)));
revoke select,update,delete on public.product_analytics from anon,authenticated;
create index if not exists product_analytics_event_time_idx on public.product_analytics(event_name,created_at desc);

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='trip_checklist_items') then
    alter publication supabase_realtime add table public.trip_checklist_items;
  end if;
end $$;

create table if not exists public.trip_file_retention (
  path text primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  kind text not null,
  created_by uuid not null references public.profiles(id),
  retain_until timestamptz not null,
  created_at timestamptz not null default now()
);
alter table public.trip_file_retention enable row level security;
create policy "members read trip file retention" on public.trip_file_retention for select to authenticated using(public.is_trip_member(trip_id));
create policy "users register own trip files" on public.trip_file_retention for insert to authenticated with check(created_by=auth.uid() and public.is_trip_member(trip_id));
create policy "users remove own trip file records" on public.trip_file_retention for delete to authenticated using(created_by=auth.uid() or exists(select 1 from public.trips t where t.id=trip_id and t.owner_id=auth.uid()));
