-- Production polish: activity history, recoverable deletes and stay-poll winners.

create table if not exists public.trip_activity_log (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  kind text not null,
  message text not null,
  entity_type text,
  entity_id uuid,
  created_at timestamptz not null default now()
);
alter table public.trip_activity_log enable row level security;
drop policy if exists "members read trip activity" on public.trip_activity_log;
create policy "members read trip activity" on public.trip_activity_log for select to authenticated
using (public.is_trip_member(trip_id));
create index if not exists trip_activity_log_trip_time_idx on public.trip_activity_log(trip_id,created_at desc);

create table if not exists public.trip_trash (
  id uuid primary key default gen_random_uuid(),
  trip_id uuid not null references public.trips(id) on delete cascade,
  item_type text not null check(item_type in ('stop','expense','collection')),
  item_id uuid not null,
  label text not null,
  payload jsonb not null,
  deleted_by uuid not null references public.profiles(id),
  deleted_at timestamptz not null default now(),
  expires_at timestamptz not null default now()+interval '7 days'
);
alter table public.trip_trash enable row level security;
drop policy if exists "owners manage trip trash" on public.trip_trash;
create policy "owners manage trip trash" on public.trip_trash for all to authenticated
using (exists(select 1 from public.trips t where t.id=trip_id and t.owner_id=auth.uid()))
with check (exists(select 1 from public.trips t where t.id=trip_id and t.owner_id=auth.uid()));
create index if not exists trip_trash_trip_time_idx on public.trip_trash(trip_id,deleted_at desc);

create or replace function public.delete_trip_item(target_trip uuid,target_type text,target_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare item jsonb; children jsonb:='[]'::jsonb; item_label text; allowed boolean;
begin
  select exists(select 1 from public.trip_members m where m.trip_id=target_trip and m.user_id=auth.uid() and
    (m.trip_role='owner' or (target_type='stop' and m.trip_role='planner') or (target_type in ('expense','collection') and m.trip_role='treasurer'))) into allowed;
  if not allowed then raise exception 'ไม่มีสิทธิ์ลบรายการนี้'; end if;
  if target_type='stop' then
    select to_jsonb(s),s.title into item,item_label from public.trip_stops s where s.id=target_id and s.trip_id=target_trip;
  elsif target_type='expense' then
    select to_jsonb(e),e.title into item,item_label from public.expenses e where e.id=target_id and e.trip_id=target_trip;
    select coalesce(jsonb_agg(to_jsonb(p)),'[]'::jsonb) into children from public.expense_participants p where p.expense_id=target_id;
  elsif target_type='collection' then
    select to_jsonb(c),c.title into item,item_label from public.collections c where c.id=target_id and c.trip_id=target_trip;
    select coalesce(jsonb_agg(to_jsonb(p)),'[]'::jsonb) into children from public.collection_payments p where p.collection_id=target_id;
  else raise exception 'ประเภทรายการไม่ถูกต้อง'; end if;
  if item is null then raise exception 'ไม่พบรายการ'; end if;
  delete from public.trip_trash where expires_at<now();
  insert into public.trip_trash(trip_id,item_type,item_id,label,payload,deleted_by)
  values(target_trip,target_type,target_id,item_label,jsonb_build_object('record',item,'children',children),auth.uid());
  if target_type='stop' then delete from public.trip_stops where id=target_id;
  elsif target_type='expense' then delete from public.expenses where id=target_id;
  else delete from public.collections where id=target_id; end if;
  insert into public.trip_activity_log(trip_id,actor_id,kind,message,entity_type,entity_id)
  values(target_trip,auth.uid(),'delete','ลบ “'||item_label||'” (กู้คืนได้ 7 วัน)',target_type,target_id);
end; $$;

create or replace function public.restore_trip_item(target_trash uuid)
returns void language plpgsql security definer set search_path=public as $$
declare saved public.trip_trash%rowtype;
begin
  select q.* into saved from public.trip_trash q join public.trips t on t.id=q.trip_id
  where q.id=target_trash and q.expires_at>now() and t.owner_id=auth.uid();
  if not found then raise exception 'ไม่พบรายการกู้คืนหรือหมดอายุแล้ว'; end if;
  if saved.item_type='stop' then
    insert into public.trip_stops select * from jsonb_populate_record(null::public.trip_stops,saved.payload->'record') on conflict(id) do nothing;
  elsif saved.item_type='expense' then
    insert into public.expenses select * from jsonb_populate_record(null::public.expenses,saved.payload->'record') on conflict(id) do nothing;
    insert into public.expense_participants select * from jsonb_populate_recordset(null::public.expense_participants,saved.payload->'children') on conflict do nothing;
  elsif saved.item_type='collection' then
    insert into public.collections select * from jsonb_populate_record(null::public.collections,saved.payload->'record') on conflict(id) do nothing;
    insert into public.collection_payments select * from jsonb_populate_recordset(null::public.collection_payments,saved.payload->'children') on conflict do nothing;
  end if;
  insert into public.trip_activity_log(trip_id,actor_id,kind,message,entity_type,entity_id)
  values(saved.trip_id,auth.uid(),'restore','กู้คืน “'||saved.label||'”',saved.item_type,saved.item_id);
  delete from public.trip_trash where id=target_trash;
end; $$;

create or replace function public.log_trip_change()
returns trigger language plpgsql security definer set search_path=public as $$
declare trip uuid; label text; kind_name text;
begin
  trip:=new.trip_id;
  label:=coalesce(new.title,'รายการ');
  kind_name:=case when tg_op='INSERT' then 'เพิ่ม' else 'แก้ไข' end;
  insert into public.trip_activity_log(trip_id,actor_id,kind,message,entity_type,entity_id)
  values(trip,auth.uid(),lower(tg_op),kind_name||' “'||label||'”',tg_table_name,new.id);
  return new;
end; $$;
drop trigger if exists log_trip_stop_change on public.trip_stops;
create trigger log_trip_stop_change after insert or update on public.trip_stops for each row execute function public.log_trip_change();
drop trigger if exists log_expense_change on public.expenses;
create trigger log_expense_change after insert or update on public.expenses for each row execute function public.log_trip_change();
drop trigger if exists log_collection_change on public.collections;
create trigger log_collection_change after insert or update on public.collections for each row execute function public.log_trip_change();

alter table public.stay_polls add column if not exists winner_option_id uuid references public.stay_poll_options(id) on delete set null;
alter table public.stay_polls add column if not exists closed_at timestamptz;
create or replace function public.select_stay_poll_winner(poll_token uuid,option_id uuid)
returns void language plpgsql security definer set search_path=public as $$
declare target_poll public.stay_polls%rowtype;
begin
  select p.* into target_poll from public.stay_polls p join public.trips t on t.id=p.trip_id
  where p.token=poll_token and t.owner_id=auth.uid();
  if not found then raise exception 'ไม่พบโพลหรือไม่มีสิทธิ์'; end if;
  if not exists(select 1 from public.stay_poll_options o where o.id=option_id and o.poll_id=target_poll.id) then raise exception 'ตัวเลือกไม่ถูกต้อง'; end if;
  update public.stay_polls set winner_option_id=option_id,status='closed',closed_at=now() where id=target_poll.id;
  insert into public.trip_activity_log(trip_id,actor_id,kind,message,entity_type,entity_id)
  select target_poll.trip_id,auth.uid(),'vote_winner','เลือก “'||o.name||'” เป็นที่พักของทริป','stay_poll_options',o.id from public.stay_poll_options o where o.id=option_id;
end; $$;

revoke all on function public.delete_trip_item(uuid,text,uuid) from public;
revoke all on function public.restore_trip_item(uuid) from public;
revoke all on function public.select_stay_poll_winner(uuid,uuid) from public;
grant execute on function public.delete_trip_item(uuid,text,uuid) to authenticated;
grant execute on function public.restore_trip_item(uuid) to authenticated;
grant execute on function public.select_stay_poll_winner(uuid,uuid) to authenticated;

create or replace function public.stay_poll_snapshot(poll_token uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb;
begin
  select jsonb_build_object(
    'id',p.id,'token',p.token,'title',p.title,'status',p.status,'winner_option_id',p.winner_option_id,'closed_at',p.closed_at,
    'member_count',(select count(*) from public.trip_members m where m.trip_id=p.trip_id),
    'voter_count',(select count(distinct v.voter_key) from public.stay_poll_votes v where v.poll_id=p.id),
    'trip',jsonb_build_object('name',t.name,'start_date',t.start_date,'end_date',t.end_date),
    'options',coalesce((select jsonb_agg(jsonb_build_object(
      'id',o.id,'name',o.name,'details',o.details,'pros',o.pros,'cons',o.cons,'price',o.price,'image_url',o.image_url,
      'votes',(select count(*) from public.stay_poll_votes v where v.option_id=o.id)
    ) order by o.sort_order,o.id) from public.stay_poll_options o where o.poll_id=p.id),'[]'::jsonb)
  ) into result from public.stay_polls p join public.trips t on t.id=p.trip_id where p.token=poll_token;
  if result is null then raise exception 'ไม่พบลิงก์โหวตหรือหมดอายุ'; end if;
  return result;
end; $$;

create or replace function public.list_stay_polls(target_trip uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare result jsonb;
begin
  if not exists(select 1 from public.trips where id=target_trip and owner_id=auth.uid()) then raise exception 'เฉพาะแอดมินทริปเท่านั้น'; end if;
  select coalesce(jsonb_agg(jsonb_build_object(
    'id',p.id,'token',p.token,'title',p.title,'status',p.status,'winner_option_id',p.winner_option_id,'closed_at',p.closed_at,'created_at',p.created_at,
    'voter_count',(select count(distinct v.voter_key) from public.stay_poll_votes v where v.poll_id=p.id),
    'options',coalesce((select jsonb_agg(jsonb_build_object('id',o.id,'name',o.name,'details',o.details,'pros',o.pros,'cons',o.cons,'price',o.price,'image_url',o.image_url,'votes',(select count(*) from public.stay_poll_votes v where v.option_id=o.id)) order by o.sort_order,o.id) from public.stay_poll_options o where o.poll_id=p.id),'[]'::jsonb)
  ) order by p.created_at desc),'[]'::jsonb) into result from public.stay_polls p where p.trip_id=target_trip;
  return result;
end; $$;

grant execute on function public.stay_poll_snapshot(uuid) to anon,authenticated;
grant execute on function public.list_stay_polls(uuid) to authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='trip_activity_log') then
    alter publication supabase_realtime add table public.trip_activity_log;
  end if;
end $$;
