create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions(user_id);
alter table public.push_subscriptions enable row level security;

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions"
  on public.push_subscriptions for all to authenticated
  using (user_id = auth.uid())
  with check (user_id = auth.uid());

create table if not exists public.push_notification_events (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  actor_id uuid not null references auth.users(id) on delete cascade,
  event_type text not null check (event_type in ('online','movement')),
  created_at timestamptz not null default now()
);

create index if not exists push_notification_events_throttle_idx
  on public.push_notification_events(trip_id, actor_id, event_type, created_at desc);

alter table public.push_notification_events enable row level security;
revoke all on public.push_notification_events from anon, authenticated;

