-- Trip Pulse: private location history, automatic cleanup and realtime activity.
-- Run once in the Supabase SQL editor.

create table if not exists public.trip_location_history (
  id bigint generated by default as identity primary key,
  trip_id uuid not null references public.trips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  latitude double precision not null,
  longitude double precision not null,
  accuracy_m double precision,
  recorded_at timestamptz not null default now()
);

alter table public.trip_location_history enable row level security;

drop policy if exists "members read trip location history" on public.trip_location_history;
create policy "members read trip location history"
on public.trip_location_history for select to authenticated
using (public.is_trip_member(trip_id));

-- History is written by the trigger only. Clients cannot forge another member's route.
create or replace function public.capture_trip_location_history()
returns trigger language plpgsql security definer set search_path = public
as $$
declare last_point public.trip_location_history%rowtype;
begin
  if not new.sharing_enabled then return new; end if;
  select * into last_point from public.trip_location_history
  where trip_id=new.trip_id and user_id=new.user_id
  order by recorded_at desc limit 1;

  if not found
     or last_point.recorded_at < now() - interval '2 minutes'
     or abs(last_point.latitude-new.latitude) > 0.00009
     or abs(last_point.longitude-new.longitude) > 0.00009 then
    insert into public.trip_location_history(trip_id,user_id,latitude,longitude,accuracy_m,recorded_at)
    values(new.trip_id,new.user_id,new.latitude,new.longitude,new.accuracy_m,new.updated_at);
  end if;
  return new;
end;
$$;

drop trigger if exists capture_trip_location_history on public.live_locations;
create trigger capture_trip_location_history
after insert or update of latitude,longitude,sharing_enabled on public.live_locations
for each row execute function public.capture_trip_location_history();

create index if not exists trip_location_history_trip_time_idx
on public.trip_location_history(trip_id,recorded_at);
create index if not exists trip_location_history_user_time_idx
on public.trip_location_history(trip_id,user_id,recorded_at);

create table if not exists public.trip_route_stats (
  trip_id uuid not null references public.trips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  distance_m double precision not null default 0,
  last_latitude double precision,
  last_longitude double precision,
  updated_at timestamptz not null default now(),
  primary key(trip_id,user_id)
);
alter table public.trip_route_stats enable row level security;
drop policy if exists "members read trip route stats" on public.trip_route_stats;
create policy "members read trip route stats" on public.trip_route_stats
for select to authenticated using(public.is_trip_member(trip_id));

create or replace function public.update_trip_route_stats()
returns trigger language plpgsql security definer set search_path=public
as $$
declare segment_m double precision := 0;
begin
  if new.sharing_enabled and tg_op='UPDATE' and old.sharing_enabled then
    segment_m := 6371000 * 2 * asin(sqrt(least(1,
      power(sin(radians(new.latitude-old.latitude)/2),2) +
      cos(radians(old.latitude))*cos(radians(new.latitude))*power(sin(radians(new.longitude-old.longitude)/2),2)
    )));
    if segment_m > 10000 then segment_m := 0; end if; -- ignore impossible GPS jumps
  end if;
  insert into public.trip_route_stats(trip_id,user_id,distance_m,last_latitude,last_longitude,updated_at)
  values(new.trip_id,new.user_id,segment_m,new.latitude,new.longitude,new.updated_at)
  on conflict(trip_id,user_id) do update set
    distance_m=public.trip_route_stats.distance_m+excluded.distance_m,
    last_latitude=excluded.last_latitude,last_longitude=excluded.last_longitude,updated_at=excluded.updated_at;
  return new;
end;
$$;
drop trigger if exists update_trip_route_stats on public.live_locations;
create trigger update_trip_route_stats after insert or update of latitude,longitude,sharing_enabled
on public.live_locations for each row execute function public.update_trip_route_stats();

-- Called when a member opens a trip. It disables sharing after the trip and
-- removes precise points older than 24 hours. The aggregated recap remains
-- available from completed stops and expenses even after precise points expire.
create or replace function public.cleanup_trip_locations(target_trip uuid)
returns void language plpgsql security definer set search_path = public
as $$
begin
  if not public.is_trip_member(target_trip) then raise exception 'ไม่มีสิทธิ์เข้าถึงทริปนี้'; end if;
  update public.live_locations l set sharing_enabled=false,updated_at=now()
  from public.trips t where l.trip_id=t.id and t.id=target_trip and t.end_date < current_date and l.sharing_enabled;
  delete from public.live_locations where trip_id=target_trip and updated_at < now()-interval '24 hours';
  delete from public.trip_location_history where trip_id=target_trip and recorded_at < now()-interval '24 hours';
  update public.trip_route_stats set last_latitude=null,last_longitude=null
  where trip_id=target_trip and updated_at < now()-interval '24 hours';
end;
$$;

revoke all on function public.cleanup_trip_locations(uuid) from public;
grant execute on function public.cleanup_trip_locations(uuid) to authenticated;

do $$
declare table_name text;
begin
  foreach table_name in array array['trip_stops','trip_stop_checkins','expenses','collections','collection_payments'] loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename=table_name
    ) then execute format('alter publication supabase_realtime add table public.%I',table_name);
    end if;
  end loop;
end $$;
